version: '3'
services:
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/conf/main.conf:/etc/nginx/conf.d/default.conf
      - ./www:/www
    links:
      - php
    depends_on:
      - php
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal
  php:
    image: php:fpm-alpine
    build: ./php
    volumes:
      - ./www:/www
    environment:
      - REDIS_ADDRESS=${REDIS_ADDRESS}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - MEMCACHED_ADDRESS=${MEMCACHED_ADDRESS}
      - MEMCACHED_PORT=${MEMCACHED_PORT}
    links:
      - redis
      - memcached
  redis:
    image: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
  memcached:
    image: memcached
